services:
  - type: web
    name: zesha-app
    buildCommand: npx expo export --platform web
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
